# Generated by Django 6.0.6 on 2026-06-24 23:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex: 2025-2026', max_length=20, unique=True)),
                ('est_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(help_text='Ex: 5ème Humanités', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=255)),
                ('code_national', models.CharField(max_length=100, unique=True)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('code_matiere', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Numéro de Téléphone')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTEUR', 'Directeur des Études'), ('PROFESSEUR', 'Professeur'), ('PARENT', 'Parent/Tuteur')], default='PARENT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_evenement', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_evenement', models.CharField(choices=[('SCOLAIRE', 'Scolaire'), ('HORS_SCOLAIRE', 'Hors-Scolaire')], default='SCOLAIRE', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(default="À l'école", max_length=200)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='ecole.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_frais', models.CharField(max_length=150)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='ecole.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut_inscription', models.CharField(choices=[('ACTIF', 'Actif'), ('ABANDON', 'Abandon'), ('TRANSFERE', 'Transféré')], default='ACTIF', max_length=20)),
                ('frais_inscription_paye', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='ecole.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='ecole.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faute', models.CharField(max_length=255)),
                ('sanction', models.CharField(blank=True, max_length=255, null=True)),
                ('date_incident', models.DateField()),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_disciplinaires', to='ecole.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=15)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='ecole.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('P1', '1ère Période'), ('P2', '2ème Période'), ('EXAM_S1', 'Examen Semestre 1'), ('P3', '3ème Période'), ('P4', '4ème Période'), ('EXAM_S2', 'Examen Semestre 2')], max_length=10)),
                ('note_obtenue', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('points_max', models.IntegerField(default=20)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ecole.inscription')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type_canal', models.CharField(choices=[('SMS', 'SMS'), ('IN_APP', 'In-App'), ('EMAIL', 'Email')], default='IN_APP', max_length=10)),
                ('statut_envoi', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échoué')], default='EN_ATTENTE', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_option', models.CharField(help_text='Ex: Commerciale & Gestion', max_length=100)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ecole.ecole')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='option_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecole.optionscolaire'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('MPESA', 'M-Pesa'), ('ORANGE', 'Orange Money'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANQUE', 'Banque')], max_length=15)),
                ('statut', models.CharField(choices=[('PENDING', 'En Attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échoué')], default='PENDING', max_length=15)),
                ('frais_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.fraisscolaire')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ecole.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='ParentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_parente', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR_LEGAL', 'Tuteur Légal'), ('ONCLE_TANTE', 'Oncle / Tante')], default='TUTEUR_LEGAL', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jour', models.DateField()),
                ('statut_presence', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En Retard'), ('JUSTIFIE', 'Justifié')], default='PRESENT', max_length=15)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.horaire')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='ecole.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_prof', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(help_text='Ex: Licencié, Gradué, Docteur', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_professeur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='horaire',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='ecole.professeur'),
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_domicile', models.TextField()),
                ('enfants', models.ManyToManyField(related_name='tuteurs', through='ecole.ParentEleve', to='ecole.eleve')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_tuteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parenteleve',
            name='tuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.tuteur'),
        ),
        migrations.AlterUniqueTogether(
            name='parenteleve',
            unique_together={('tuteur', 'eleve')},
        ),
    ]
